# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       Rajath Chandrahasa
author:      Rajath Chandrahasa
email:       ''
description: ''
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://rajath.blog' # The base hostname & protocol for your site

# Social links
twitter_username: rajath_c
github:    'rajathc'
instagram: ''
linkedin:  ''

markdown:  kramdown
permalink: pretty
paginate:  10
future:    true
timezone:  Asia/Kolkata

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - fonts/sligoil-main/documentation
  - fonts/sligoil-main/README.md
  - fonts/sligoil-main/COPYRIGHT.md
  - fonts/sligoil-main/TRADEMARKS.md
  - scripts
  - images-backup
  - node_modules
  - package.json
  - package-lock.json
  - IMAGE-OPTIMIZATION.md
  - GIF-CONVERSION.md
  - README-OPTIMIZATION.md

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
